apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCBSuxuU8um+db1pumKUEb9ZzPUXDwuPSsFYU9ALrXKJI+yi2ZwY/OwKWVBVFA6A+0WsfgQn9DJa3K2jPs081I9aLBI+XgShL6QgD5eAOSoXAqWrzx2KTw6UVQCtH5naNwclkVfp0gkHuCmlNW6TQPuNeeMB3oCVgHkRbieTn/N3Q9+toLhJ5dY28hYBSI8Y9t5UnGoFk6HAWg6AiP2gaTSSx7PrjjrssfF1pzk8KepeDOTVGa70zc6j9BqZ1XPJqxHrGA1OD/QabNjLK2qKqq75VnyrX3nRJol6wBtm+bvPANkVkfdk1/u0DuWbrYfq1HzqeeOnmGYYjP7HVLbmrvN0tctVwK58fXKM9VbMoWVEc2MazTD7dfxyuMSk7HcKh/bUomjVuxZbH8i/9+7lynGUNGYuCDw2reQ8EC4yxk7XdXjQuwXhMAPz2iSvEz9GZKxVTFwn2l5Zq5b/+kzoHkxjwY0bAyWFP1iI+M2W4OJTWsx8+RzJKNisuIHFZcz36l4F+cDVqT4FeY92NPZsbSL8800xPWgQ6Sx2im3DNFUuBh2B2Ik8vEkTxHlZDIeYIRRuhG5Bo8yBwgd2JnWIPctF+T1OJTTWcIH5powNygULRHaKMDk2KPiK7h1ux0ThTIMlo7Ac+YPnPCrqZnWh/nzrrq2dvSfbuamo9tHsxow0Qy4bEL0BWuIYnBLBdXZf5qepnUV7wmJfg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

