kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-b2bi-psp
  namespace: b2bi-prod
  uid: a8d4182b-1282-4a3c-a2f7-8f52ce664eb6
  resourceVersion: '360511'
  creationTimestamp: '2022-11-10T19:57:28Z'
  labels:
    app: ibm-b2bi-psp
  annotations:
    argocd.argoproj.io/sync-wave: '275'
subjects:
  - kind: ServiceAccount
    name: b2bi
    namespace: b2bi-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-b2bi-psp